### ISSUE TITLE
can't run the project

### ISSUE THREAD

**Issue by emam4** [dyte-io/react-samples#18]
there's no div in the scripts, so "npm run div" (as mentioned in the READ.ME) won't work

![image](https://github.com/dyte-io/react-samples/assets/119869254/63cb3519-e592-4462-9e98-612a24015106)

**Comment by thebongy** [comment]
Hi, as mentioned in the README, you need to `cd` inside a folder in the samples folder, and then run `npm install` and `npm run dev` there. (Eg: https://github.com/dyte-io/react-samples/blob/27e3fabdb27226d448adf40a3e7ed0960be10a9f/samples/chat/package.json#L7) These are not supposed to be run on the root folder of the repo.

**Comment by AlexanderKapelyukhovskiy** [comment]
I think this issue could be closed
